# https://github.com/iinsertNameHere/catnap

[stats]
username  = {icon = " ", name = "usr", color = "(RD)"}
hostname  = {icon = " ", name = "hst", color = "(YW)"}
uptime    = {icon = " ", name = "upt", color = "(BE)"}
sep_1 = "SEPARATOR"
distro    = {icon = " ", name = "dis", color = "(GN)"}
# kernel    = {icon = " ", name = "ker", color = "(MA)"}
desktop   = {icon = " ", name = "des", color = "(CN)"}
terminal  = {icon = " ", name = "ter", color = "(RD)"}
shell     = {icon = " ", name = "shl", color = "(MA)"}
# packages  = {icon = " ", name = "packages", color = "(RD)"}
# weather   = {icon = " ", name = "weather", color = "(BE)"}
# gpu       = {icon = "󱔐 ", name = "gpu", color = "(MA)"}
# cpu       = {icon = " ", name = "cpu", color = "(RD)"}
# battery   = {icon = " ", name = "battery", color = "(GN)"}
# memory    = {icon = " ", name = "mem", color = "(YW)"}
# disk_0    = {icon = " ", name = "disk", color = "(GN)"}
sep_2 = "SEPARATOR"
colors    = {icon = " ", name = "clr", color = "!DT!", symbol = ""}

# -- resource intensive
# packages
# weather (requires curl & an emoji font)
# gpu
# -- doesn't work on macOS & bsd
# memory
# disk

[misc]
borderstyle = "line" # [line, dashed, dotted, noborder, doubleline]
layout = "Inline" # [Inline, ArtOnTop, StatsOnTop]
stats_margin_top = 0 # dictates how many lines the StatsBlock will be placed down
# location = "" # fetch weather, leave empty to use the location of your IP; (https://wttr.in/:help)

