source = /home/vah/.cache/wal/colors-hyprland.conf

monitor=eDP-1,preferred,0x0,1

# https://wiki.hyprland.org/Configuring/Variables/
input {
  kb_layout = de
  kb_variant = nodeadkeys
  kb_options = grp:win_space_toggle
  follow_mouse = 2
  sensitivity = 0.3 # range: -1.0 - 1.0; default 0
  repeat_rate = 40
  repeat_delay = 250
  touchpad {
    disable_while_typing = 1
    natural_scroll = 1
    tap-to-click = 1
    drag_lock = 0
  }
}

# https://wiki.hyprland.org/Configuring/Variables/
general {
  gaps_in = 8
  gaps_out = 12
  border_size = 0
  resize_on_border = true
  col.active_border = $color6 $color3 90deg
  col.inactive_border = rgba(000000A0)
  layout = dwindle
}

# https://wiki.hyprland.org/Configuring/Variables/ for more
decoration {
  fullscreen_opacity = 1.0
  active_opacity = 1.0
  inactive_opacity = 0.75
  rounding = 12

  dim_inactive = true
  dim_strength = 0.25

  blur {
    enabled = true
    size = 1
    passes = 5
    ignore_opacity = true
    new_optimizations = true
  }

  shadow {
    enabled = false
    range = 16
    render_power = 2
    offset = 2 2
    color = rgba(0, 0, 0, 255)
  }
}

animations {
  enabled = yes

  # bezier configurations
  bezier = smooth, 0.15, 0.3, 0.15, 1
  bezier = shot, 0.2, 1, 0.2, 1

  # fade
  animation = fade, 1, 5, smooth
  # windows
  animation = windows, 1, 6, shot, slide
  animation = windowsOut, 1, 6, smooth, popin 90%
  # workspaces
  animation = workspaces, 1, 5, smooth, slidefade 15%
  # borders
  animation = border, 1, 8, smooth
  animation = borderangle, 1, 8, smooth, once
}


# https://wiki.hyprland.org/Configuring/Dwindle-Layout/
dwindle {
  preserve_split = yes
}

# https://wiki.hyprland.org/Configuring/Master-Layout/
master {
  new_status = master
}

# https://wiki.hyprland.org/Configuring/Variables/
misc {
  force_default_wallpaper = 1
  disable_hyprland_logo = true
  mouse_move_enables_dpms = true
  vrr = 2
  enable_swallow = true
  swallow_regex = ^(foot|alacritty|ghostty)$
}
