# -- connectivity & services --
exec-once = blueman-applet
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# -- daemons --
exec-once = awww-daemon
exec-once = waybar &
exec-once = hypridle &
exec-once = clipse -listen &
exec-once = swaync &
exec-once = $HOME/.config/hypr/scripts/wallpaper-select.sh --daemon
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
