# nmcli 
windowrule = match:class ^(nm-connection-editor)$, float true, center true, size 50% 50%

# clipse
windowrule = match:class ^(clipse)$, float true, center true, size 60% 60%

# nwg-look
windowrule = match:class ^(nwg-look)$, float true, center true, size 70% 70%

# rofi
windowrule = match:class ^([Rr]ofi)$, opacity 0.9 0.6

# spotify
windowrule = match:class ^(Spotify)$, opacity 0.9 0.7

# steam
windowrule = match:class ^(steam)$, opacity 0.9 0.7

# awww
layerrule = match:namespace ^(awww)$, blur true

# rofi
layerrule = match:namespace ^(rofi)$, blur true
layerrule = match:namespace ^(rofi)$, ignore_alpha 0.0

# swaync
layerrule = match:namespace ^(swaync-control-center)$, blur true
layerrule = match:namespace ^(swaync-notification-window)$, blur true

layerrule = match:namespace ^(swaync-control-center)$, ignore_alpha 0.5
layerrule = match:namespace ^(swaync-notification-window)$, ignore_alpha 0.5
