git_protocol: ssh
editor: /usr/bin/nvim
prompt: enabled
pager: less
aliases:
    rv: '!gh repo view "$@" 2>/dev/null || echo "not logged in"'
    rvw: '!gh repo view "$@" --web 2>/dev/null || echo "not logged in"'
http_unix_socket:
browser: "/mnt/c/PROGRA~1/BraveSoftware/Brave-Browser/Application/brave.exe"
version: "1"
