general {
    ignore_dbus_inhibit = fals
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# notification listener
listener {
    timeout = 240
    on-timeout = notify-send "yawwwwnnn"
}

# lock screen listener
listener {
    timeout = 320
    on-timeout = loginctl lock-session
    on-resume = notify-send 'hai'
}

# suspend listener
listener {
    timeout = 600
    on-timeout = systemctl suspend
    on-resume = notify-send 'hai'
}
