# credit: https://github.com/zDyant/HyprNova/blob/master/.config/hypr/hyprlock.conf
source = $HOME/.cache/wal/colors-hyprland.conf

background {
    monitor =
    path = $HOME/.config/hypr/painting.png # only png supported for now
    # color = $color1

    # https://wiki.hyprland.org/Configuring/Variables/blur
    blur_size = 4
    blur_passes = 3
    noise = 0.0117
    contrast = 1.2000
    brightness = 0.8000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

# hours
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%H") </big></b>"
    color = $color6
    font_size = 112
    font_family = Geist Mono 10
    shadow_passes = 3
    shadow_size = 4

    position = 0, 220
    halign = center
    valign = center
}

# minutes
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%M") </big></b>"
    color = $color6
    font_size = 112
    font_family = Geist Mono 10
    shadow_passes = 3
    shadow_size = 4

    position = 0, 80
    halign = center
    valign = center
}

# today
label {
    monitor =
    text = cmd[update:18000000] echo "<b><big> "$(date +'%A')" </big></b>"
    color = $color7
    font_size = 22
    font_family = JetBrainsMono Nerd Font 10

    position = 0, -40 # adjust the y value as desired
    halign = center
    valign = center
}

# week
label {
    monitor =
    text = cmd[update:18000000] echo "<b> "$(date +'%d %b')" </b>"
    color = $color7
    font_size = 18
    font_family = JetBrainsMono Nerd Font 10

    position = 0, -80 # adjust the y value as desired
    halign = center
    valign = center
}

# degrees
label {
    monitor =
    text = cmd[update:18000000] echo "<i>feels like $(curl -s 'wttr.in/Lahr?format=%t' | tr -d '+')</i>"
    color = $color7
    font_size = 18
    font_family = Geist Mono 10

    position = 0, 40
    halign = center
    valign = bottom
}

input-field {
    monitor =
    size = 300, 45
    outline_thickness = 2

    dots_size = 0.3     # 0.2 - 0.8
    dots_spacing = 0.7  # 0.0 - 1.0
    dots_center = true
    dots_rouding = -1

    rounding = 18
    outer_color = $color0
    inner_color = $color0
    font_color = $color6
    check_color = $color4
    capslock_color = $color5
    fade_on_empty = true
    placeholder_text =

    position = 0, 100
    halign = center
    valign = bottom
}

label {
    text = cmd[update:500] bash -c '[ "$(cat /sys/class/leds/input*::capslock/brightness 2>/dev/null)" = "1" ] && echo "CAPS"'
    color = $color5
    font_size = 12
    font_family = Geist Mono

    position = 0, 150
    halign = center
    valign = bottom
}
