return {
  "nvim-treesitter/nvim-treesitter",
  opts = function(_, opts)
    opts.ensure_installed = {
      "bash",
      "c",
      "css",
      "diff",
      "dockerfile",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "html",
      "http",
      "javascript",
      "just",
      "json",
      "jq",
      "lua",
      "luadoc",
      "make",
      "markdown",
      "markdown_inline",
      "nasm",
      "nginx",
      "passwd",
      "python",
      "requirements",
      "regex",
      "rust",
      "ssh_config",
      "toml",
      "typst",
      "vim",
      "yaml",
      "zsh",
    }
  end,
  auto_install = false,
}
